#pragma once

#define JOURNEY_KEY_SPACE   32
#define JOURNEY_KEY_APOSTROPHE   39 /* ' */
#define JOURNEY_KEY_COMMA   44 /* , */
#define JOURNEY_KEY_MINUS   45 /* - */
#define JOURNEY_KEY_PERIOD   46 /* . */
#define JOURNEY_KEY_SLASH   47 /* / */
#define JOURNEY_KEY_0   48
#define JOURNEY_KEY_1   49
#define JOURNEY_KEY_2   50
#define JOURNEY_KEY_3   51
#define JOURNEY_KEY_4   52
#define JOURNEY_KEY_5   53
#define JOURNEY_KEY_6   54
#define JOURNEY_KEY_7   55
#define JOURNEY_KEY_8   56
#define JOURNEY_KEY_9   57
#define JOURNEY_KEY_SEMICOLON   59 /* ; */
#define JOURNEY_KEY_EQUAL   61 /* = */
#define JOURNEY_KEY_A   65
#define JOURNEY_KEY_B   66
#define JOURNEY_KEY_C   67
#define JOURNEY_KEY_D   68
#define JOURNEY_KEY_E   69
#define JOURNEY_KEY_F   70
#define JOURNEY_KEY_G   71
#define JOURNEY_KEY_H   72
#define JOURNEY_KEY_I   73
#define JOURNEY_KEY_J   74
#define JOURNEY_KEY_K   75
#define JOURNEY_KEY_L   76
#define JOURNEY_KEY_M   77
#define JOURNEY_KEY_N   78
#define JOURNEY_KEY_O   79
#define JOURNEY_KEY_P   80
#define JOURNEY_KEY_Q   81
#define JOURNEY_KEY_R   82
#define JOURNEY_KEY_S   83
#define JOURNEY_KEY_T   84
#define JOURNEY_KEY_U   85
#define JOURNEY_KEY_V   86
#define JOURNEY_KEY_W   87
#define JOURNEY_KEY_X   88
#define JOURNEY_KEY_Y   89
#define JOURNEY_KEY_Z   90
#define JOURNEY_KEY_LEFT_BRACKET   91 /* [ */
#define JOURNEY_KEY_BACKSLASH   92 /* \ */
#define JOURNEY_KEY_RIGHT_BRACKET   93 /* ] */
#define JOURNEY_KEY_GRAVE_ACCENT   96 /* ` */
#define JOURNEY_KEY_WORLD_1   161 /* non-US #1 */
#define JOURNEY_KEY_WORLD_2   162 /* non-US #2 */
#define JOURNEY_KEY_ESCAPE   256
#define JOURNEY_KEY_ENTER   257
#define JOURNEY_KEY_TAB   258
#define JOURNEY_KEY_BACKSPACE   259
#define JOURNEY_KEY_INSERT   260
#define JOURNEY_KEY_DELETE   261
#define JOURNEY_KEY_RIGHT   262
#define JOURNEY_KEY_LEFT   263
#define JOURNEY_KEY_DOWN   264
#define JOURNEY_KEY_UP   265
#define JOURNEY_KEY_PAGE_UP   266
#define JOURNEY_KEY_PAGE_DOWN   267
#define JOURNEY_KEY_HOME   268
#define JOURNEY_KEY_END   269
#define JOURNEY_KEY_CAPS_LOCK   280
#define JOURNEY_KEY_SCROLL_LOCK   281
#define JOURNEY_KEY_NUM_LOCK   282
#define JOURNEY_KEY_PRINT_SCREEN   283
#define JOURNEY_KEY_PAUSE   284
#define JOURNEY_KEY_F1   290
#define JOURNEY_KEY_F2   291
#define JOURNEY_KEY_F3   292
#define JOURNEY_KEY_F4   293
#define JOURNEY_KEY_F5   294
#define JOURNEY_KEY_F6   295
#define JOURNEY_KEY_F7   296
#define JOURNEY_KEY_F8   297
#define JOURNEY_KEY_F9   298
#define JOURNEY_KEY_F10   299
#define JOURNEY_KEY_F11   300
#define JOURNEY_KEY_F12   301
#define JOURNEY_KEY_F13   302
#define JOURNEY_KEY_F14   303
#define JOURNEY_KEY_F15   304
#define JOURNEY_KEY_F16   305
#define JOURNEY_KEY_F17   306
#define JOURNEY_KEY_F18   307
#define JOURNEY_KEY_F19   308
#define JOURNEY_KEY_F20   309
#define JOURNEY_KEY_F21   310
#define JOURNEY_KEY_F22   311
#define JOURNEY_KEY_F23   312
#define JOURNEY_KEY_F24   313
#define JOURNEY_KEY_F25   314
#define JOURNEY_KEY_KP_0   320
#define JOURNEY_KEY_KP_1   321
#define JOURNEY_KEY_KP_2   322
#define JOURNEY_KEY_KP_3   323
#define JOURNEY_KEY_KP_4   324
#define JOURNEY_KEY_KP_5   325
#define JOURNEY_KEY_KP_6   326
#define JOURNEY_KEY_KP_8   328
#define JOURNEY_KEY_KP_9   329
#define JOURNEY_KEY_KP_DECIMAL   330
#define JOURNEY_KEY_KP_DIVIDE   331
#define JOURNEY_KEY_KP_MULTIPLY   332
#define JOURNEY_KEY_KP_SUBTRACT   333
#define JOURNEY_KEY_KP_ADD   334
#define JOURNEY_KEY_KP_ENTER   335
#define JOURNEY_KEY_KP_EQUAL   336
#define JOURNEY_KEY_LEFT_SHIFT   340
#define JOURNEY_KEY_LEFT_CONTROL   341
#define JOURNEY_KEY_LEFT_ALT   342
#define JOURNEY_KEY_LEFT_SUPER   343
#define JOURNEY_KEY_RIGHT_SHIFT   344
#define JOURNEY_KEY_RIGHT_CONTROL   345
#define JOURNEY_KEY_RIGHT_ALT   346
#define JOURNEY_KEY_RIGHT_SUPER   347
#define JOURNEY_KEY_MENU   348